name: prova_flutter
description: Aplicativo de Controle de Abastecimento e Veículos - scaffold inicial
publish_to: "none"
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3
  provider: ^6.0.5
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  firebase_database: ^10.4.0
  intl: ^0.18.1 # Para formatação de datas e moedas

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
